apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-server
    spec:
      containers:
      - name: dev-server
        image: 747061988355.dkr.ecr.us-east-2.amazonaws.com/devops:latest
        ports:
        - name: http-port
          containerPort: 8080
          protocol: TCP
